"""report.py — render an analysis.Result into the TESTING_PLAN markdown skeleton."""

from __future__ import annotations

import datetime
import os

REPORTS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "..", "reports", "sim")
REPORTS = os.path.normpath(REPORTS)


def _verdict(passed):
    if passed is True:
        return "PASS"
    if passed is False:
        return "FAIL"
    return "CONDITIONAL (see recommendation)"


def render(res, preset: str) -> str:
    today = datetime.date.today().isoformat()
    rows = "\n".join(
        f"| {q} | {e} | {m} | {u} |" for (q, e, m, u) in res.metrics
    ) or "| — | — | — | — |"
    plot = f"\n![{res.name}](./{res.plot})\n" if res.plot else ""
    md = f"""# {res.title} — {today} — sim

> Auto-generated by `sim/scripts/run_all.py` (preset `{preset}`). Do not hand-edit;
> regenerate with `python sim/scripts/run_all.py`.

## Objective
{res.objective}

## Setup
{res.setup}

## Method
{res.method}

## Results

| Quantity | Expected | Measured | Unit |
|----------|----------|----------|------|
{rows}
{plot}
## Pass / Fail
**Criterion:** {res.criterion}

**Result: {_verdict(res.passed)}** — {res.summary}

## Anomalies & notes
{res.notes}

## Next
{res.nextstep or "—"}
"""
    return md


def write(res, preset: str) -> str:
    os.makedirs(REPORTS, exist_ok=True)
    path = os.path.join(REPORTS, f"{res.name}.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(render(res, preset))
    return path
