#!/usr/bin/env python
"""run_all.py — single headless entry point for the Track-B SPICE harness.

    python sim/scripts/run_all.py [--preset pt100_100u] [--ngspice PATH]

Steps, fully reproducibly:
  1. Regenerate sim/netlists/_generated_params.inc from sim/scripts/config.py + rtd.py.
  2. Run every deck headless: ngspice -b -o reports/sim/<name>.log netlists/<name>.cir
     (cwd = sim/, raw wrdata -> sim/scratch/, gitignored).
  3. Parse each result, decide pass/fail, plot, and write reports/sim/<name>.md.
  4. Print a summary table; exit non-zero if any test FAILS (CONDITIONAL does not fail).

ngspice discovery order: --ngspice arg, $NGSPICE, PATH, the conda 'ngspice' env. KiCad's
ngspice.dll is NOT a CLI and cannot be used here (see docs/sessions/trackB.md).

WAVE-3 HOOK: at fabrication, re-point the decks from the modeled cell to the KiCad-
exported netlist sim/netlists/ref200-rtd.net (see sim/README.md "Wave 3").
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SIM_DIR = os.path.dirname(HERE)
REPO = os.path.dirname(SIM_DIR)
NETLISTS = os.path.join(SIM_DIR, "netlists")
SCRATCH = os.path.join(SIM_DIR, "scratch")
REPORTS = os.path.join(REPO, "reports", "sim")

sys.path.insert(0, HERE)
import config          # noqa: E402
import rtd             # noqa: E402
import analysis        # noqa: E402
import report          # noqa: E402

DECKS = [
    "01_dc_op", "02_ratiometric", "03_accuracy_rref", "04_compliance_corner",
    "05_transient_settling", "06_noise", "07_crosstalk",
]


def find_ngspice(cli_arg=None) -> str:
    cands = []
    if cli_arg:
        cands.append(cli_arg)
    if os.environ.get("NGSPICE"):
        cands.append(os.environ["NGSPICE"])
    on_path = shutil.which("ngspice")
    if on_path:
        cands.append(on_path)
    # conda env created for Track B
    conda = os.path.expanduser(
        r"~\AppData\Local\anaconda3\envs\ngspice\Library\bin\ngspice.exe")
    cands.append(conda)
    for c in cands:
        if c and os.path.exists(c):
            return c
    raise SystemExit(
        "ngspice CLI not found. Install standalone ngspice (e.g. "
        "`conda create -n ngspice -c conda-forge ngspice`) or pass --ngspice PATH. "
        "KiCad's ngspice.dll is not a CLI and cannot be used.")


def write_params_inc(cfg, dest=None) -> None:
    """Regenerate the shared params include from config + CVD physics. Writes to the
    committed copy in sim/netlists by default, or to `dest` (the local rundir copy)."""
    if dest is None:
        dest = os.path.join(NETLISTS, "_generated_params.inc")
    typ = cfg["rtd_type"]
    rmin = rtd.r_of_t(config.T_MIN_C, typ)
    rmax = rtd.r_of_t(config.T_MAX_C, typ)
    r_ref_dev = cfg["r_ref_tol"] + cfg["r_ref_tempco"] * config.T_BOARD_DELTA_C
    v_lo = cfg["i_exc"] * rmin
    v_hi = cfg["i_exc"] * rmax
    pairs = {
        "i_exc": cfg["i_exc"], "r_ref": cfg["r_ref"], "v_rail": cfg["v_rail"],
        "v_rail_min": cfg["v_rail"] * 0.95, "rout_src": cfg["rout_src"],
        "filt_r": config.FILTER_R, "filt_c": config.FILTER_C,
        "r_rtd_min": round(rmin, 6), "r_rtd_max": round(rmax, 6),
        "r_rtd_nom": round(config.PRESETS[config.ACTIVE]["r_ref"], 6),
        "star_gnd_r": config.STAR_GND_R, "r_ref_dev": r_ref_dev,
        "v_sense_lo": v_lo, "v_sense_hi": v_hi, "mux_dwell": config.MUX_DWELL_S,
    }
    lines = ["* AUTO-GENERATED by sim/scripts/run_all.py from config.py preset "
             f"'{config.ACTIVE}'. DO NOT EDIT BY HAND -- edit config.py and re-run.",
             "* .param drives device lines; .csparam exposes the same value to .control."]
    for k, v in pairs.items():
        lines.append(f".param {k}={v:g}")
    for k in pairs:
        lines.append(f".csparam {k}={{{k}}}")
    with open(dest, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def stage_rundir(cfg):
    """Create a LOCAL (non-OneDrive) working copy of the decks/models and regenerate the
    params include into it. ngspice writes its raw wrdata here, because rapid `wrdata` file
    creation in the OneDrive-synced tree silently drops files (the `-o` logs survive, the
    new data files do not). Returns the temp rundir; caller cleans it up."""
    rundir = tempfile.mkdtemp(prefix="ref200sim_")
    shutil.copytree(NETLISTS, os.path.join(rundir, "netlists"))
    shutil.copytree(os.path.join(SIM_DIR, "models"), os.path.join(rundir, "models"))
    scratch = os.path.join(rundir, "scratch")
    os.makedirs(scratch, exist_ok=True)
    write_params_inc(cfg, os.path.join(rundir, "netlists", "_generated_params.inc"))
    # ngspice does not reliably resolve a relative `wrdata` path against cwd, so rewrite
    # the staged deck copies to an ABSOLUTE scratch target (the committed decks keep the
    # clean relative path). Forward slashes work on Windows ngspice.
    abs_scratch = scratch.replace("\\", "/")
    for name in DECKS:
        p = os.path.join(rundir, "netlists", f"{name}.cir")
        with open(p) as fh:
            txt = fh.read()
        txt = txt.replace("wrdata scratch/", f"wrdata {abs_scratch}/")
        with open(p, "w") as fh:
            fh.write(txt)
    return rundir


def run_deck(ngspice: str, name: str, rundir: str) -> int:
    """Run one deck headless in the local rundir. Both the `-o` log and the `wrdata` data
    are written LOCALLY (writing either to the OneDrive-synced tree during a rapid batch
    causes ngspice to silently drop the wrdata files); the log is copied to reports/sim
    afterwards. Success is judged from the log, not the process exit code (ngspice on the
    Windows conda build intermittently returns a spurious non-zero code on a clean run)."""
    local_log = os.path.join(rundir, f"{name}.log")
    deck = os.path.join("netlists", f"{name}.cir")
    subprocess.run([ngspice, "-b", "-o", local_log, deck], cwd=rundir,
                   capture_output=True, text=True)
    shutil.copyfile(local_log, os.path.join(REPORTS, f"{name}.log"))
    bad = ("error", "fatal", "aborted", "no such", "is not in the circuit",
           "cannot compute")
    with open(local_log, encoding="utf-8", errors="replace") as fh:
        txt = fh.read().lower()
    if any(b in txt for b in bad):
        return 1
    if "data rows" not in txt and "executed from .control" not in txt:
        return 1                        # analysis line never ran
    return 0


def main() -> int:
    try:                                  # reports use °C/Ω; keep the console from choking
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    ap = argparse.ArgumentParser()
    ap.add_argument("--preset", default=None, help="config preset (overrides ACTIVE)")
    ap.add_argument("--ngspice", default=None, help="path to ngspice CLI")
    args = ap.parse_args()

    if args.preset:
        if args.preset not in config.PRESETS:
            raise SystemExit(f"unknown preset {args.preset}; have {list(config.PRESETS)}")
        config.ACTIVE = args.preset
    cfg = config.active()

    ngspice = find_ngspice(args.ngspice)
    os.makedirs(SCRATCH, exist_ok=True)
    os.makedirs(REPORTS, exist_ok=True)

    print(f"== Track-B SPICE harness ==  preset={config.ACTIVE}  ngspice={ngspice}")
    write_params_inc(cfg)                      # keep the committed copy current
    rundir = stage_rundir(cfg)                 # local working copy (off OneDrive)
    analysis.SCRATCH = os.path.join(rundir, "scratch")  # analysis reads raw data here
    try:
        # 1+2: run decks
        run_failures = []
        for name in DECKS:
            rc = run_deck(ngspice, name, rundir)
            status = "ok" if rc == 0 else "DECK ERROR"
            print(f"  run {name:24s} {status}")
            if rc:
                run_failures.append(name)
        if run_failures:
            print(f"\nABORT: deck(s) failed to run cleanly: {run_failures}")
            return 2

        # 3: analyse + report
        results = [fn(cfg) for fn in analysis.ALL]
        for res in results:
            report.write(res, config.ACTIVE)
    finally:
        shutil.rmtree(rundir, ignore_errors=True)

    # 4: summary
    print("\n== Summary ==")
    any_fail = False
    for res in results:
        v = "PASS" if res.passed is True else ("FAIL" if res.passed is False else "COND")
        any_fail = any_fail or (res.passed is False)
        print(f"  [{v:4s}] {res.name:24s} {res.summary}")
    print(f"\nReports: reports/sim/*.md   Figures: reports/sim/*.png")
    return 1 if any_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())